package uniandes.edu.co.proyecto.modelo;

public enum TipoServicio {
    CONSULTA_GENERAL,
    CONSULTA_ESPECIALISTA,
    CONSULTA_CONTROL,
    CONSULTA_URGENCIAS,
    EXAMEN_DIAGNOSTICO,
    TERAPIAS,
    PROCEDIMIENTO_ESPECIALISADO,
}
